#!/usr/bin/env bash
# resolve-mechanics.sh — Deterministic mechanical consequence resolver
# Computes trait/condition/bond changes from resolved dice tiers + dramaturg guidance.
# Pure arithmetic — no LLM needed.
#
# Responsibilities:
#   - Read resolved-skeleton.yaml (rolled tiers per character per beat)
#   - Read dramaturg-guidance.yaml character_mechanics (tier → mechanical consequence mappings)
#   - Parse mechanical notation strings via regex for trait/condition/bond changes
#   - Build cumulative running state across beats
#   - Write turn-mechanics.yaml to workspace
#
# Usage: resolve-mechanics.sh <workspace>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─────────────────────────────────────────────
# HELP
# ─────────────────────────────────────────────

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<EOF
Usage: resolve-mechanics.sh <workspace>

Reads resolved-skeleton.yaml and dramaturg-guidance.yaml from <workspace>.
Parses character_mechanics notation for trait/condition/bond changes.
Writes turn-mechanics.yaml with cumulative running state per beat.

Mechanical note patterns recognized:
  TRAIT N→M              Direct value change (deepening/shift)
  TRAIT pressure +N      Pressure increment
  TRAIT pressure N→M     Pressure direct set
  TRAIT evolution: TYPE  Evolution event (pressure resets to 0)
  CONDITION phase: X→Y   Condition phase change
  CONDITION intensity: X→Y  Condition intensity change
  DIMENSION N→M          Bond dimension change
  DIMENSION +N           Bond dimension increment

Unrecognized patterns are logged as warnings and skipped.
EOF
  exit 0
fi

# ─────────────────────────────────────────────
# ARGS
# ─────────────────────────────────────────────

WORKSPACE="${1:?Usage: resolve-mechanics.sh <workspace>}"

SKELETON="$WORKSPACE/resolved-skeleton.yaml"
GUIDANCE="$WORKSPACE/dramaturg-guidance.yaml"
OUTPUT="$WORKSPACE/turn-mechanics.yaml"

# ─────────────────────────────────────────────
# VALIDATION
# ─────────────────────────────────────────────

if [[ ! -f "$SKELETON" ]]; then
  echo "ERROR: resolved-skeleton.yaml not found at $SKELETON" >&2
  exit 1
fi

if [[ ! -f "$GUIDANCE" ]]; then
  echo "ERROR: dramaturg-guidance.yaml not found at $GUIDANCE" >&2
  exit 1
fi

# ─────────────────────────────────────────────
# TEMP FILES (workspace-local)
# ─────────────────────────────────────────────

TMPDIR="$WORKSPACE/.mech-tmp-$$"
mkdir -p "$TMPDIR"
TMPCOUNTER_FILE="$TMPDIR/.counter"
echo "0" > "$TMPCOUNTER_FILE"

cleanup() { rm -rf "$TMPDIR" 2>/dev/null || true; }
trap cleanup EXIT

mktmp() {
  local c
  c=$(( $(cat "$TMPCOUNTER_FILE") + 1 ))
  echo "$c" > "$TMPCOUNTER_FILE"
  local f="$TMPDIR/tmp-${c}"
  : > "$f"
  echo "$f"
}

# ─────────────────────────────────────────────
# READ TURN NUMBER
# ─────────────────────────────────────────────

TURN=$(yq -r '.turn // "unknown"' "$SKELETON")

# ─────────────────────────────────────────────
# ENUMERATE BEATS
# ─────────────────────────────────────────────

BEATS=()
while IFS= read -r beat; do
  [[ -n "$beat" ]] && BEATS+=("$beat")
done < <(yq -r '.skeleton | keys | .[]' "$SKELETON" 2>/dev/null)

if [[ ${#BEATS[@]} -eq 0 ]]; then
  echo "WARN: No beats found in skeleton — writing empty mechanics" >&2
  cat > "$OUTPUT" <<EOF
# turn-mechanics.yaml — generated by resolve-mechanics.sh
turn: $TURN
running_state: {}
EOF
  echo "Empty mechanics written to: $OUTPUT"
  exit 0
fi

# ─────────────────────────────────────────────
# PARSE mechanical_note
# ─────────────────────────────────────────────
# Extracts structured changes from natural language notes.
# Each parser writes entries to a tmp file as YAML fragments.

parse_mechanical_note() {
  local character="$1"
  local note="$2"
  local trait_out="$3"
  local cond_out="$4"
  local bond_out="$5"

  # Skip empty or explicit no-change notes
  if [[ -z "$note" || "$note" == "null" ]]; then
    return
  fi

  # Normalize: collapse whitespace, strip quotes
  note=$(echo "$note" | tr '\n' ' ' | sed -E 's/[[:space:]]+/ /g; s/^"//; s/"$//')

  # Check for explicit no-change
  if echo "$note" | grep -qi "no trait change\|no change\|holds at"; then
    # Still check for other patterns below — "holds at" might coexist with bond changes
    :
  fi

  # --- TRAIT: evolution event ---
  # Pattern: TRAIT evolution: TYPE  or  TRAIT evolution — TYPE
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local trait_name event_type
    trait_name=$(echo "$match" | awk '{print $1}')
    event_type=$(echo "$match" | sed -E 's/.*evolution[: —–-]+[[:space:]]*//' | awk '{print $1}' | tr -d '.,;')
    cat >> "$trait_out" <<EOF
  - character: $character
    trait: $trait_name
    from: null
    to: 0
    event: evolution_${event_type}
EOF
  done < <(echo "$note" | grep -oE '[A-Z][A-Z_]+[[:space:]]+evolution[: —–-]+[a-z_]+' 2>/dev/null || true)

  # --- TRAIT: direct value change N→M ---
  # Pattern: TRAIT N→M  (unicode arrow or ->)
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local trait_name from_val to_val
    trait_name=$(echo "$match" | awk '{print $1}')
    from_val=$(echo "$match" | sed 's/.*[[:space:]]//' | sed 's/[→>->].*//')
    to_val=$(echo "$match" | sed 's/.*[→>->]//' | sed 's/[^0-9].*//')
    if [[ -n "$from_val" && -n "$to_val" && "$from_val" =~ ^[0-9]+$ && "$to_val" =~ ^[0-9]+$ ]]; then
      # Skip if this trait already had an evolution event
      if ! grep -q "trait: $trait_name" "$trait_out" 2>/dev/null; then
        local event="deepening"
        if (( to_val < from_val )); then
          event="reduction"
        fi
        cat >> "$trait_out" <<EOF
  - character: $character
    trait: $trait_name
    from: $from_val
    to: $to_val
    event: $event
EOF
      fi
    fi
  done < <(echo "$note" | grep -oE '[A-Z][A-Z_]+[[:space:]]+[0-9]+[[:space:]]*[→>-]+[[:space:]]*[0-9]+' 2>/dev/null || true)

  # --- TRAIT: pressure increment ---
  # Pattern: TRAIT pressure +N  or  TRAIT pressure +N (total)
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local trait_name incr
    trait_name=$(echo "$match" | awk '{print $1}')
    incr=$(echo "$match" | grep -oE '\+[0-9]+' | tr -d '+')
    if [[ -n "$incr" ]]; then
      # Extract current value if present in parenthetical like (20) or total
      local current_total
      current_total=$(echo "$note" | grep -oE "$trait_name"'[^.]*\(([0-9]+)\)' | grep -oE '[0-9]+' | tail -1 || true)
      local from_val to_val
      if [[ -n "$current_total" ]]; then
        to_val="$current_total"
        from_val=$(( current_total - incr ))
      else
        from_val="null"
        to_val="+${incr}"
      fi
      # Skip if already recorded
      if ! grep -q "trait: $trait_name" "$trait_out" 2>/dev/null; then
        cat >> "$trait_out" <<EOF
  - character: $character
    trait: $trait_name
    from: $from_val
    to: $to_val
    event: pressure_increment
EOF
      fi
    fi
  done < <(echo "$note" | grep -oE '[A-Z][A-Z_]+[[:space:]]+pressure[[:space:]]+\+[0-9]+' 2>/dev/null || true)

  # --- TRAIT: pressure direct set N→M ---
  # Pattern: TRAIT pressure N→M  or  Pressure N→M (reset)
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local trait_name from_val to_val
    trait_name=$(echo "$match" | awk '{print $1}')
    from_val=$(echo "$match" | grep -oE '[0-9]+[→>-]+' | sed 's/[→>-]//g')
    to_val=$(echo "$match" | grep -oE '[→>-]+[0-9]+' | sed 's/[→>-]//g')
    if [[ -n "$from_val" && -n "$to_val" && "$from_val" =~ ^[0-9]+$ && "$to_val" =~ ^[0-9]+$ ]]; then
      local event="pressure_change"
      if (( to_val == 0 )); then
        event="pressure_reset"
      fi
      # Skip if already recorded via evolution or direct
      if ! grep -q "trait: $trait_name" "$trait_out" 2>/dev/null; then
        cat >> "$trait_out" <<EOF
  - character: $character
    trait: $trait_name
    from: $from_val
    to: $to_val
    event: $event
EOF
      fi
    fi
  done < <(echo "$note" | grep -oE '[A-Z][A-Z_]+[[:space:]]+pressure[[:space:]]+[0-9]+[[:space:]]*[→>-]+[[:space:]]*[0-9]+' 2>/dev/null || true)

  # --- CONDITION: phase or intensity change ---
  # Pattern: CONDITION phase: X→Y  or  CONDITION intensity: X→Y
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local cond_name dim from_val to_val
    cond_name=$(echo "$match" | awk '{print $1}')
    dim=$(echo "$match" | grep -oE '(phase|intensity)' | head -1)
    from_val=$(echo "$match" | sed "s/.*${dim}:[[:space:]]*//" | sed 's/[[:space:]]*[→>-].*//')
    to_val=$(echo "$match" | sed 's/.*[→>-][[:space:]]*//' | awk '{print $1}')
    cat >> "$cond_out" <<EOF
  - character: $character
    condition: $cond_name
    dimension: $dim
    from: "$from_val"
    to: "$to_val"
EOF
  done < <(echo "$note" | grep -oE '[A-Z][A-Z_]+[[:space:]]+(phase|intensity):[[:space:]]*[^ ]+[[:space:]]*[→>-]+[[:space:]]*[^ ,;.]+' 2>/dev/null || true)

  # --- BOND: dimension change N→M ---
  # Pattern: DIMENSION N→M  (lowercase dimension names like trust, fear, warmth)
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local dim_name from_val to_val
    dim_name=$(echo "$match" | awk '{print $1}')
    from_val=$(echo "$match" | grep -oE '[0-9]+' | head -1)
    to_val=$(echo "$match" | grep -oE '[0-9]+' | tail -1)
    if [[ -n "$from_val" && -n "$to_val" && "$from_val" != "$to_val" ]]; then
      cat >> "$bond_out" <<EOF
  - character: $character
    dimension: $dim_name
    from: $from_val
    to: $to_val
EOF
    fi
  done < <(echo "$note" | grep -oiE '(trust|fear|warmth|physical|emotional|intellectual|loyalty|respect|dependence|rivalry|intimacy|power)[[:space:]]+[0-9]+[[:space:]]*[→>-]+[[:space:]]*[0-9]+' 2>/dev/null || true)

  # --- BOND: dimension increment +N ---
  while IFS= read -r match; do
    [[ -z "$match" ]] && continue
    local dim_name incr
    dim_name=$(echo "$match" | awk '{print $1}')
    incr=$(echo "$match" | grep -oE '\+[0-9]+' | tr -d '+')
    if [[ -n "$incr" ]]; then
      cat >> "$bond_out" <<EOF
  - character: $character
    dimension: $dim_name
    from: null
    to: "+${incr}"
EOF
    fi
  done < <(echo "$note" | grep -oiE '(trust|fear|warmth|physical|emotional|intellectual|loyalty|respect|dependence|rivalry|intimacy|power)[[:space:]]+\+[0-9]+' 2>/dev/null || true)
}

# ─────────────────────────────────────────────
# PROCESS BEATS
# ─────────────────────────────────────────────

RUNNING_YAML=$(mktmp)
cat > "$RUNNING_YAML" <<EOF
# turn-mechanics.yaml — generated by resolve-mechanics.sh
turn: $TURN

running_state:
EOF

WARN_COUNT=0

for beat in "${BEATS[@]}"; do
  # Get characters in this beat
  CHARACTERS=()
  while IFS= read -r char; do
    [[ -n "$char" && "$char" != "secondary" && "$char" != "world" ]] && CHARACTERS+=("$char")
  done < <(yq -r ".skeleton.\"$beat\" | keys | .[]" "$SKELETON" 2>/dev/null)

  if [[ ${#CHARACTERS[@]} -eq 0 ]]; then
    echo "WARN: Beat $beat has no characters — skipping" >&2
    WARN_COUNT=$((WARN_COUNT + 1))
    continue
  fi

  # Temp files for this beat's changes
  TRAIT_TMP=$(mktmp)
  COND_TMP=$(mktmp)
  BOND_TMP=$(mktmp)

  for character in "${CHARACTERS[@]}"; do
    # Read tier from skeleton
    tier=$(yq -r ".skeleton.\"$beat\".\"$character\".tier // \"\"" "$SKELETON")
    if [[ -z "$tier" || "$tier" == "null" ]]; then
      echo "WARN: No tier for $character in $beat — skipping" >&2
      WARN_COUNT=$((WARN_COUNT + 1))
      continue
    fi

    # Look up mechanical notation from dramaturg-guidance character_mechanics
    mech_note=$(yq -r ".character_mechanics.\"$character\".\"$tier\" // \"\"" "$GUIDANCE" 2>/dev/null)

    if [[ -z "$mech_note" || "$mech_note" == "null" ]]; then
      echo "WARN: No outcome mapping for $character/$tier in dramaturg-guidance — empty changes" >&2
      WARN_COUNT=$((WARN_COUNT + 1))
      continue
    fi

    # Parse the mechanical note
    parse_mechanical_note "$character" "$mech_note" "$TRAIT_TMP" "$COND_TMP" "$BOND_TMP"
  done

  # Build this beat's YAML block
  cat >> "$RUNNING_YAML" <<EOF
  $beat:
    trait_changes:
EOF

  if [[ -s "$TRAIT_TMP" ]]; then
    sed 's/^/    /' "$TRAIT_TMP" >> "$RUNNING_YAML"
  else
    echo "      []" >> "$RUNNING_YAML"
  fi

  cat >> "$RUNNING_YAML" <<EOF
    condition_changes:
EOF

  if [[ -s "$COND_TMP" ]]; then
    sed 's/^/    /' "$COND_TMP" >> "$RUNNING_YAML"
  else
    echo "      []" >> "$RUNNING_YAML"
  fi

  cat >> "$RUNNING_YAML" <<EOF
    bond_changes:
EOF

  if [[ -s "$BOND_TMP" ]]; then
    sed 's/^/    /' "$BOND_TMP" >> "$RUNNING_YAML"
  else
    echo "      []" >> "$RUNNING_YAML"
  fi

done

# ─────────────────────────────────────────────
# WRITE OUTPUT
# ─────────────────────────────────────────────

cp "$RUNNING_YAML" "$OUTPUT"

echo "Mechanics written to: $OUTPUT"
echo "Beats processed: ${#BEATS[@]}"
if [[ $WARN_COUNT -gt 0 ]]; then
  echo "Warnings: $WARN_COUNT (check stderr)"
fi
